# Generated by Django 6.0.3 on 2026-03-07 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitAnalyse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_rate", models.FloatField(default=0.0)),
                ("last_active", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HabitGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_target", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(default="", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="HabitReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_time", models.TimeField(null=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="profile",
        ),
        migrations.AddField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[
                    ("study", "Study"),
                    ("diet", "Diet"),
                    ("exercise", "Exercise"),
                    ("work", "Work"),
                    ("sleep", "Sleep"),
                    ("creative", "Creative"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="habit",
            name="isActive",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="habitanalyse",
            name="habit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="portfolio.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitanalyse",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_analysis",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitgoal",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="portfolio.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitgoal",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="portfolio.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitreminder",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="portfolio.habit",
            ),
        ),
        migrations.AddField(
            model_name="habitreminder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
