# Generated by Django 6.0.3 on 2026-03-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="profile",
        ),
        migrations.AddField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[
                    ("study", "Study"),
                    ("diet", "Diet"),
                    ("exercise", "Exercise"),
                    ("work", "Work"),
                    ("sleep", "Sleep"),
                    ("creative", "Creative"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
