# Generated by Django 6.0.3 on 2026-03-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_delete_profile_habit_category_habit_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="frequency",
            new_name="streak",
        ),
    ]
