# Generated by Django 6.0.3 on 2026-03-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_rename_frequency_habit_streak"),
    ]

    operations = [
        migrations.CreateModel(
            name="habitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habit", models.CharField(default="", max_length=100)),
                ("completion_rate", models.IntegerField(default=0)),
                ("last_active", models.DateTimeField()),
                ("notes", models.TextField(default="", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="habit",
            name="isActive",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="Inactive",
                max_length=100,
            ),
        ),
    ]
