# Generated by Django 6.0.3 on 2026-03-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_habitlog_habit_isactive"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitlog",
            name="completed_at",
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name="habitlog",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="portfolio.habit",
            ),
        ),
    ]
