# Generated by Django 6.0.3 on 2026-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_habitlog_completed_at_alter_habitlog_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name="habitlog",
            name="last_active",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
