# Generated by Django 6.0.3 on 2026-03-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_habit_created_at_alter_habitlog_last_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitlog",
            name="completion_rate",
        ),
        migrations.RemoveField(
            model_name="habitlog",
            name="last_active",
        ),
        migrations.AddField(
            model_name="habitlog",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="HabitAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_rate", models.FloatField(default=0.0)),
                ("last_active", models.DateField(null=True)),
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.habit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitGoals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekly_target", models.IntegerField(default=0)),
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.habit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HabitReminders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reminder_time", models.TimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.habit",
                    ),
                ),
            ],
        ),
    ]
