# Generated by Django 6.0.3 on 2026-03-06 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_remove_habitlog_completion_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habitreminders",
            name="reminder_time",
        ),
        migrations.AlterField(
            model_name="habitgoals",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="portfolio.habit",
            ),
        ),
        migrations.AlterField(
            model_name="habitreminders",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remainders",
                to="portfolio.habit",
            ),
        ),
    ]
