# Generated by Django 6.0.3 on 2026-03-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_remove_habitreminders_reminder_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habitreminders",
            name="reminder_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="habitreminders",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="portfolio.habit",
            ),
        ),
    ]
