# Generated by Django 6.0.3 on 2026-03-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_habitreminders_reminder_time_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HabitAnalysis",
            new_name="HabitAnalyse",
        ),
        migrations.RenameModel(
            old_name="HabitGoals",
            new_name="HabitGoal",
        ),
        migrations.RenameModel(
            old_name="HabitReminders",
            new_name="HabitReminder",
        ),
    ]
