# Generated by Django 6.0.3 on 2026-03-06 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_rename_habitanalysis_habitanalyse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitanalyse",
            name="habit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis",
                to="portfolio.habit",
            ),
        ),
    ]
